from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "gui" / "release_library_page.py"

text = TARGET.read_text(encoding="utf-8")

old = '''        if checked == 1:\n\n            painter.save()\n\n            # Lichtgele volledige cel\n            painter.fillRect(\n                option.rect,\n                QColor(\n                    255,\n                    235,\n                    150\n                )\n            )\n\n            # Tekstkleur\n            opt.palette.setColor(\n                QPalette.ColorRole.Text,\n                QColor(\n                    20,\n                    20,\n                    20\n                )\n            )\n\n            opt.palette.setColor(\n                QPalette.ColorRole.WindowText,\n                QColor(\n                    20,\n                    20,\n                    20\n                )\n            )\n\n            # Achtergrond transparant maken zodat de\n            # stylesheet het geel niet opnieuw overschrijft.\n            opt.backgroundBrush = Qt.BrushStyle.NoBrush\n\n            # Tekst tekenen\n            style = opt.widget.style() if opt.widget else None\n\n            if style is None:\n\n                from PySide6.QtWidgets import QApplication\n\n                style = QApplication.style()\n\n            style.drawControl(\n                QStyle.ControlElement.CE_ItemViewItem,\n                opt,\n                painter,\n                opt.widget\n            )\n\n            painter.restore()\n\n            return\n'''

new = '''        if checked == 1:\n\n            painter.save()\n\n            # KLAAR moet blijvend geel zijn, ook wanneer de rij\n            # geselecteerd is. Qt mag de selection-background dus\n            # niet over onze gele achtergrond heen tekenen.\n            painter.fillRect(\n                option.rect,\n                READY_BACKGROUND\n            )\n\n            # Zorg dat de geselecteerde staat de gele achtergrond\n            # niet opnieuw overschrijft.\n            opt.state &= ~QStyle.StateFlag.State_Selected\n            opt.state &= ~QStyle.StateFlag.State_HasFocus\n            opt.backgroundBrush = Qt.BrushStyle.NoBrush\n\n            # Donkere tekst op de gele achtergrond.\n            opt.palette.setColor(\n                QPalette.ColorRole.Text,\n                READY_FOREGROUND\n            )\n            opt.palette.setColor(\n                QPalette.ColorRole.WindowText,\n                READY_FOREGROUND\n            )\n            opt.palette.setColor(\n                QPalette.ColorRole.HighlightedText,\n                READY_FOREGROUND\n            )\n\n            style = opt.widget.style() if opt.widget else None\n\n            if style is None:\n                from PySide6.QtWidgets import QApplication\n                style = QApplication.style()\n\n            style.drawControl(\n                QStyle.ControlElement.CE_ItemViewItem,\n                opt,\n                painter,\n                opt.widget\n            )\n\n            painter.restore()\n            return\n'''

if old not in text:
    raise SystemExit("Expected Vinyl ready delegate block not found; nothing changed.")

TARGET.write_text(text.replace(old, new, 1), encoding="utf-8")
print("Vinyl KLAAR display fixed: yellow remains visible when selected.")
