from pathlib import Path

p = Path('gui/main_window.py')
s = p.read_text(encoding='utf-8-sig')
marker = '        self.apply_style()\n'
code = '''        self.apply_style()\n\n        # FORCE ONE DARK UI\n        protected = []\n        if hasattr(self, 'detail_page'):\n            protected = [\n                getattr(self.detail_page, 'checked_button', None),\n                getattr(self.detail_page, 'review_checklist', None),\n            ]\n\n        def clear_local_styles(widget):\n            if widget not in protected:\n                widget.setStyleSheet('')\n            for child in widget.findChildren(QWidget):\n                if child not in protected:\n                    child.setStyleSheet('')\n                clear_local_styles(child)\n\n        clear_local_styles(self.library_page)\n        clear_local_styles(self.detail_page)\n        clear_local_styles(self.discogs_page)\n\n        self.setStyleSheet(self.styleSheet() + '''\n            QWidget { background-color: #09090c; color: #f5f5f7; font-family: "Segoe UI"; font-size: 15px; }\n            QMainWindow, QWidget#centralWidget, QWidget#rightContainer, QStackedWidget#pageStack, QWidget#homePage { background-color: #09090c; }\n            QWidget#sidebar, QWidget#topBar { background-color: #101014; }\n            QLabel { color: #f5f5f7; }\n            QLineEdit, QComboBox, QSpinBox, QTextEdit, QPlainTextEdit { background-color: #121216; color: #ffffff; border: 1px solid #34343d; }\n            QTableWidget { background-color: #0d0d11; alternate-background-color: #141419; color: #ffffff; }\n            QHeaderView::section { background-color: #17171d; color: #ffffff; }\n            QPushButton { background-color: #18181e; color: #f5f5f7; border: 1px solid #34343d; }\n            QPushButton:hover { background-color: #202026; border: 1px solid #d84b91; }\n            QPushButton#navButton { min-height: 56px; background-color: #101014; color: #f5f5f7; }\n            QPushButton#navButton[active="true"] { background-color: #19191f; color: #ffffff; border: 1px solid #d84b91; }\n            QLabel#navIcon { color: #d0d0d8; font-size: 30px; font-weight: 700; }\n            QLabel#navText { color: #ffffff; font-size: 16px; font-weight: 600; }\n            QGroupBox, QFrame#dashboardCard, QFrame#dashboardSection, QFrame#statusPanel { background-color: #111116; color: #f5f5f7; }\n            QScrollArea, QScrollArea > QWidget, QScrollArea > QWidget > QWidget { background-color: #09090c; border: none; }\n        ''')\n'''
if s.count(marker) != 1:
    raise RuntimeError(f'apply_style marker expected 1, found {s.count(marker)}')
if '# FORCE ONE DARK UI' not in s:
    s = s.replace(marker, code, 1)
s = s.replace('        icon_label.setFixedWidth(\n            24\n        )', '        icon_label.setFixedWidth(\n            42\n        )')
p.write_text(s, encoding='utf-8-sig')
print('ECHTE UNIFORME DONKERE INTERFACE TOEGEVOEGD')
